spring.application.name=back-rpa-chat-comprasgov

#spring.datasource.url=jdbc:h2:mem:comprasgov;MODE=PostgreSQL;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
#spring.datasource.driverClassName=org.h2.Driver
#spring.datasource.username=sa
#spring.datasource.password=

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.open-in-view=false
spring.jpa.defer-datasource-initialization=true

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

app.notifications.email.to=
app.notifications.whatsapp.webhook-url=

#spring.datasource.url=jdbc:mysql://vistahml.cxgl1c7blbdf.us-east-1.rds.amazonaws.com:3306/vista?serverTimezone=TimeZone&useLegacyDatetimeCode=false&serverTimezone=America/Sao_Paulo
#spring.datasource.username=vistahml
#spring.datasource.password=Vistahml123456

spring.datasource.url=jdbc:mysql://vista.cxgl1c7blbdf.us-east-1.rds.amazonaws.com:3306/vista?serverTimezone=TimeZone&useLegacyDatetimeCode=false&serverTimezone=America/Sao_Paulo
spring.datasource.username=vista
spring.datasource.password=wr=3x[=il4A

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.max-wait=24000
spring.datasource.max-active=60
spring.datasource.max-idle=30
spring.datasource.min-idle=15
spring.datasource.min-evicttable-idle-time-millis=30
spring.datasource.testOnBorrow=true
spring.datasource.validationQuery=SELECT 1

app.govbr.cpf = 06303344127
app.govbr.senha = Rfmh05046@

comprasnet.cpf=06303344127
comprasnet.senha=Rfmh05046@